module.exports = {
  // 공통
  NULL_VALUE: '필수 항목을 모두 입력해주세요',
  OUT_OF_VALUE: '파라미터 값이 잘못되었습니다',
  TOKEN_EMPTY: '토큰이 없습니다',
  TOKEN_INVALID: '토큰이 유효하지 않습니다',
  TOKEN_EXPIRED: '토큰이 만료되었습니다',
  NO_USER_ID: '유저 아이디가 없습니다',
  INVALID_USER: '잘못된 유저 정보입니다',
  FORBIDDEN: '잘못된 접근입니다',
  NO_USER: '존재하지 않는 유저입니다',
  INTERNAL_SERVER_ERROR: '서버 내 오류',
  ACCESS_TOKEN_EXPIRED: '액세스 토큰이 만료되었습니다',

  // Service
  GET_TEAM_COUNT_SUCCESS: '대기중인 팀 수 조회에 성공하였습니다',
  GET_SERVICE_APPLY_STATUS_SUCCESS: '매칭 신청 상황 조회에 성공하였습니다',

  // Auth
  NO_CODE: '인가코드가 없습니다',
  CREATE_USER_SUCCESS: '회원가입에 성공하였습니다',
  LOGIN_USER_SUCCESS: '로그인에 성공하였습니다',
  DELETE_USER_SUCCESS: '유저 회원탈퇴에 성공하였습니다',
  NOT_EXPIRED_TOKEN: '만료되지 않은 토큰입니다',
  INVALID_GRANT_TYPE: '올바르지 않은 허가 유형입니다',
  REFRESH_TOKEN_SUCCESS: '토큰 재발급에 성공하였습니다',
  SIGNOUT_USER_SUCCESS: '유저 로그아웃에 성공하였습니다',

  // User
  SAVE_USER_PHONE_SUCCESS: '유저 핸드폰 번호 저장에 성공하였습니다',
  GET_USER_SUCCESS: '유저 정보 조회에 성공하였습니다',
  SAVE_USER_PRIVACY_SUCCESS: '유저 개인 정보 저장 및 수정에 성공하였습니다',

  // Team
  SAVE_USER_SUCCESS: '유저 정보 저장에 성공하였습니다',
  SAVE_USER_PREFERENCE_SUCCESS: '유저 선호 정보 저장에 성공하였습니다',
  SAVE_USER_APPLY_SUCCESS: '유저 매칭 신청 정보 저장에 성공하였습니다',
  IS_MATCHING_USER: '매칭 진행중인 유저입니다',
  IS_MATCHED_USER: '이미 매칭 완료된 유저입니다',
  NO_OURTEAM: '우리팀 정보가 존재하지 않습니다',
  GET_TEAM_APPLY_SUCCESS: '팀 매칭 신청 정보 조회에 성공하였습니다',
  UPDATE_USER_APPLY_SUCCESS: '유저 매칭 신청 정보 수정에 성공하였습니다',
  NO_APPLY: '해당 유저의 매칭 신청 정보가 없습니다',
  NO_APPLY_TEAM: '해당 팀의 매칭 신청 정보가 없습니다',
  GET_TEAM_MATCHING_STATUS_SUCCESS: '팀 매칭 상태 조회에 성공하였습니다',
  GET_OURTEAM_ID_SUCCESS: '유저의 우리팀 아이디 조회에 성공하였습니다',
  GET_PARTNER_TEAM_ID_SUCCESS: '우리팀의 상대팀 아이디 조회에 성공하였습니다',
  NO_PARTNER_TEAM: '상대팀 정보가 없습니다',
  GET_MATCHING_RESULT_SUCCESS: '매칭 결과 조회에 성공하였습니다',
  NO_RESULT: '해당 팀의 매칭 결과가 없습니다',
  REAPPLY_SUCCESS: '팀 매칭 재신청에 성공하였습니다',
  GET_TEAM_MATCHING_PAGE_SUCCESS: '팀 매칭 상태 페이지 조회에 성공하였습니다',
  ALREADY_RESPONEDED_TEAM: '이미 수락 또는 거절한 팀입니다',
  MATCHING_ACCEPT_SUCCESS: '매칭 수락하기에 성공하였습니다',
  MATCHING_REFUSE_SUCCESS: '매칭 거절하기에 성공하였습니다',
  QUIT_APPLY_SUCCESS: '매칭 그만두기에 성공하였습니다',
  SAVE_REFUSE_REASON_SUCCESS: '매칭 거절 이유 보내기에 성공하였습니다',

  // Admin
  ADMIN_NO_RESULT: '조회 결과가 없습니다',
  GET_MALE_TWO_TEAM_UNCHECKED_APPLY_SUCCESS: '가신청 남자팀 2:2 매칭 신청 정보 전체 조회에 성공하였습니다',
  GET_MALE_THREE_TEAM_UNCHECKED_APPLY_SUCCESS: '가신청 남자팀 3:3 매칭 신청 정보 전체 조회에 성공하였습니다',
  GET_FEMALE_TWO_TEAM_UNCHECKED_APPLY_SUCCESS: '가신청 여자팀 2:2 매칭 신청 정보 전체 조회에 성공하였습니다',
  GET_FEMALE_THREE_TEAM_UNCHECKED_APPLY_SUCCESS: '가신청 여자팀 3:3 매칭 신청 정보 전체 조회에 성공하였습니다',
  CHECK_TEAM_SUCCESS: '매칭 신청 승인하기에 성공하였습니다',
  GET_MALE_TWO_TEAM_APPLY_SUCCESS: '남자팀 2:2 매칭 신청 정보 전체 조회에 성공하였습니다',
  GET_MALE_THREE_TEAM_APPLY_SUCCESS: '남자팀 3:3 매칭 신청 정보 전체 조회에 성공하였습니다',
  GET_FEMALE_TWO_TEAM_APPLY_SUCCESS: '여자팀 2:2 매칭 신청 정보 전체 조회에 성공하였습니다',
  GET_FEMALE_THREE_TEAM_APPLY_SUCCESS: '여자팀 3:3 매칭 신청 정보 전체 조회에 성공하였습니다',
  GET_MATCHING_SUCCESS_MALE_TEAM_SUCCESS: '매칭 완료된 남자팀 정보 전체 조회에 성공하였습니다',
  GET_MATCHING_SUCCESS_FEMALE_TEAM_SUCCESS: '매칭 완료된 여자팀 정보 전체 조회에 성공하였습니다',
  GET_MATCHING_FAIL_MALE_TEAM_SUCCESS: '매칭 실패한 남자팀 정보 전체 조회에 성공하였습니다',
  GET_MATCHING_FAIL_FEMALE_TEAM_SUCCESS: '매칭 실패한 여자팀 정보 전체 조회에 성공하였습니다',
  MATCH_TEAM_SUCCESS: '팀 매칭하기에 성공하였습니다',
  FAIL_TEAM_SUCCESS: '팀 매칭 실패 처리에 성공하였습니다',
  ALREADY_MATCHED_USER: '이미 매칭 완료된 유저입니다',
  DELETE_MATCHING_SUCCESS: '매칭 정보 삭제하기에 성공하였습니다',
  UPDATE_SERVICE_APPLY_STATUS_SUCCESS: '서비스 매칭 신청 가능 상태 변경에 성공하였습니다',
  GET_SERVICE_APPLY_STATUS_SUCCESS: '서비스 매칭 신청 가능 상태 조회에 성공하였습니다',
  REVERT_MATCH_TEAM_SUCCESS: '팀 매칭 완료에서 매칭중으로 되돌리기에 성공하였습니다',
  REVERT_FAIL_TEAM_SUCCESS: '팀 매칭 실패에서 매칭중으로 되돌리기에 성공하였습니다',
  GET_MATCHING_PENDING_MALE_TEAM_SUCCESS: '매칭 수락 대기중인 남자팀 정보 전체 조회에 성공하였습니다',
  GET_MATCHING_PENDING_FEMALE_TEAM_SUCCESS: '매칭 수락 대기중인 여자팀 정보 전체 조회에 성공하였습니다',
};
