export const Mbties = [
  { name: 'ENFJ', id: 1 },
  { name: 'ENTJ', id: 2 },
  { name: 'ENFP', id: 3 },
  { name: 'ENTP', id: 4 },
  { name: 'ESFP', id: 5 },
  { name: 'ESFJ', id: 6 },
  { name: 'ESTP', id: 7 },
  { name: 'ESTJ', id: 8 },
  { name: 'INFP', id: 9 },
  { name: 'INFJ', id: 10 },
  { name: 'INTP', id: 11 },
  { name: 'ISTP', id: 12 },
  { name: 'ISFP', id: 13 },
  { name: 'ISFJ', id: 14 },
  { name: 'ISTJ', id: 15 },
  { name: 'INTJ', id: 16 },
];
