export enum MatchingStatus {
  APPLIED = 'APPLIED', // 매칭 조회3
  FAILED = 'FAILED', // 매칭 조회4
  MATCHED = 'MATCHED', // 매칭 조회5
  OURTEAM_ACCEPTED = 'OURTEAM_ACCEPTED', // 매칭 조회6
  SUCCEEDED = 'SUCCEEDED', // 매칭 조회7
  PARTNER_TEAM_REFUSED = 'PARTNER_TEAM_REFUSED', // 매칭 조회8
  OURTEAM_REFUSED = 'OURTEAM_REFUSED', // 매칭 조회11
  NOT_RESPONDED = 'NOT_RESPONDED', // 매칭 조회12
}
